### ISSUE TITLE
All Functions Legend: Filtered levels

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/goshawk#191] opened 2023-03-06 16:59 UTC
### What happened?

2022_10_13 filtering an AMR level out does **not** remove it from the legend. this is unexpected/undesirable
![image](https://user-images.githubusercontent.com/40777373/223177659-974fa869-1f16-44c0-8527-4217f39a4ff5.png)

2022_06_09 filtering an AMR level out **does** remove it from the legend. this is expected and desirable
![image](https://user-images.githubusercontent.com/40777373/223177724-024f232b-4465-42b0-b1dc-8002204739a9.png)

### sessionInfo()

```R
see sample app behavior on rsconnect.roche.com. no session info available but here is text I copied out of the interface.

2022_10_13
Created Oct 14, 2022 11:41am (GMT-08:00) Last Deployed Oct 14, 2022 11:41am (GMT-08:00)
Shiny application
GUID 67055b29-c05c-44f9-8108-6632446a0707
R version 4.1.1

2022_06_09
Created Jun 9, 2022 3:13pm (GMT-08:00) Last Deployed Jun 9, 2022 3:58pm (GMT-08:00)
Shiny application
GUID 3b221526-03e5-4009-9aed-410e7f554bcb
R version 4.0.3
```

### Relevant log output

```R
no log output accessible from sample apps given my account was not used to publish.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by npaszty** [comment] 2023-04-25 16:34
@donyunardi 
can we get a status on this issue. we are on the cusp of deploying another Lupus data mart with it's specific app that includes the goshawk package.

**Comment by donyunardi** [comment] 2023-04-26 05:58
Using teal families at `main`, I can't reproduce the error and the legend behaves correctly:

![image](https://user-images.githubusercontent.com/8597300/234459656-5067f7ed-0516-44b6-bd25-868b97e83ec1.png)

We plan to release teal framework this increment and once we do, we need to find a way on how BEE user can bring the latest version to BEE.

**Comment by donyunardi** [comment] 2023-04-26 14:31
Upon discussion with @chlebowa, the issue seems to be with `ggplot2`.
I tested and confirmed this using 2022_10_13 snapshot.

Solution is to install `ggplot2` in your R libraries and call it specifically in the beginning of your app:
```r
library(ggplot2, lib.loc = "<path to your local R library>")
```

**Comment by chlebowa** [comment] 2023-04-26 14:35
I talked to IDR about this some time ago, maybe nudge them again?

**Comment by donyunardi** [comment] 2023-04-28 19:40
Sure, let's handle this internally.
Communicated solution with OP and it works.
Closing issue.

**Closed by donyunardi** 2023-04-28 19:40 UTC
Labels: bug, core
